name: Node.js CI release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: npm install and build
      run: |
        npm ci
        npm run build --if-present
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: chrome_extension.zip
        path: build
        retention-days: 3
    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Download the artifact
      uses: actions/download-artifact@v1
      with:
        name: chrome_extension.zip
        path: ./
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: chrome_extension.zip
        asset_name: chrome_extension.zip
        asset_content_type: application/zip
